#### Importing Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('./dataset.csv')
y = df.iloc[:, -1].values
df

age           job   marital            education default housing loan  \
0       49   blue-collar   married             basic.9y      no      no   no   
1       37  entrepreneur   married    university.degree      no      no   no   
2       78       retired   married             basic.4y      no      no   no   
3       36        admin.   married    university.degree      no     yes   no   
4       59       retired  divorced    university.degree      no      no   no   
...    ...           ...       ...                  ...     ...     ...  ...   
32945   28      services    single          high.school      no     yes   no   
32946   52    technician   married  professional.course      no     yes   no   
32947   54        admin.   married             basic.9y      no      no  yes   
32948   29        admin.   married    university.degree      no      no   no   
32949   35        admin.   married    university.degree      no      no  yes   

         contact month day_of_week  duration  campaign  pdays  previous  \
0       cellular   nov         wed       227         4    999         0   
1      telephone   nov         wed       202         2    999         1   
2       cellular   jul         mon      1148         1    999         0   
3      telephone   may         mon       120         2    999         0   
4       cellular   jun         tue       368         2    999         0   
...          ...   ...         ...       ...       ...    ...       ...   
32945   cellular   jul         tue       192         1    999         0   
32946   cellular   nov         fri        64         1    999         1   
32947   cellular   jul         mon       131         4    999         0   
32948  telephone   may         fri       165         1    999         0   
32949  telephone   jun         tue       544         3    999         0   

          poutcome    y  
0      nonexistent   no  
1          failure   no  
2      nonexistent  yes  
3      nonexistent   no  
4      nonexistent   no  
...            ...  ...  
32945  nonexistent   no  
32946      failure   no  
32947  nonexistent   no  
32948  nonexistent   no  
32949  nonexistent   no  

[32950 rows x 16 columns]

In [3]:
df['marital'].nunique()

3

In [4]:
y

array(['no', 'no', 'yes', ..., 'no', 'no', 'no'], dtype=object)

#### Encoding Categorical Data

##### Encoding Independent Variables

In [5]:
df1 = pd.get_dummies(df['job'])
df2 = pd.get_dummies(df['marital'])
df3 = pd.get_dummies(df['education'])
df4 = pd.get_dummies(df['default'])
df5 = pd.get_dummies(df['housing'])
df6 = pd.get_dummies(df['loan'])
df7 = pd.get_dummies(df['contact'])
df8 = pd.get_dummies(df['month'])
df9 = pd.get_dummies(df['day_of_week'])
df10 = pd.get_dummies(df['poutcome'])
pd.get_dummies(df['job'])

result = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9], axis=1, join='inner')

temp_df1 = df[['age']]
temp_df1

temp_df2 = df[['duration', 'campaign', 'pdays', 'previous']]
temp_df2

final_df = pd.concat([temp_df1, result, temp_df2, df10], axis=1, join='inner')
final_df

age  admin.  blue-collar  entrepreneur  housemaid  management  retired  \
0       49       0            1             0          0           0        0   
1       37       0            0             1          0           0        0   
2       78       0            0             0          0           0        1   
3       36       1            0             0          0           0        0   
4       59       0            0             0          0           0        1   
...    ...     ...          ...           ...        ...         ...      ...   
32945   28       0            0             0          0           0        0   
32946   52       0            0             0          0           0        0   
32947   54       1            0             0          0           0        0   
32948   29       1            0             0          0           0        0   
32949   35       1            0             0          0           0        0   

       self-employed  services  student  ...  thu  tue  wed  duration  \
0                  0         0        0  ...    0    0    1       227   
1                  0         0        0  ...    0    0    1       202   
2                  0         0        0  ...    0    0    0      1148   
3                  0         0        0  ...    0    0    0       120   
4                  0         0        0  ...    0    1    0       368   
...              ...       ...      ...  ...  ...  ...  ...       ...   
32945              0         1        0  ...    0    1    0       192   
32946              0         0        0  ...    0    0    0        64   
32947              0         0        0  ...    0    0    0       131   
32948              0         0        0  ...    0    0    0       165   
32949              0         0        0  ...    0    1    0       544   

       campaign  pdays  previous  failure  nonexistent  success  
0             4    999         0        0            1        0  
1             2    999         1        1            0        0  
2             1    999         0        0            1        0  
3             2    999         0        0            1        0  
4             2    999         0        0            1        0  
...         ...    ...       ...      ...          ...      ...  
32945         1    999         0        0            1        0  
32946         1    999         1        1            0        0  
32947         4    999         0        0            1        0  
32948         1    999         0        0            1        0  
32949         3    999         0        0            1        0  

[32950 rows x 52 columns]

In [6]:
x = final_df.iloc[:, :].values

In [7]:
x

array([[49,  0,  1, ...,  0,  1,  0],
       [37,  0,  0, ...,  1,  0,  0],
       [78,  0,  0, ...,  0,  1,  0],
       ...,
       [54,  1,  0, ...,  0,  1,  0],
       [29,  1,  0, ...,  0,  1,  0],
       [35,  1,  0, ...,  0,  1,  0]], dtype=int64)

##### Encoding Dependent Variables

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [9]:
y

array([0, 0, 1, ..., 0, 0, 0])

#### Splitting Dataset

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

#### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# ---------- Logistic Regression ----------

In [12]:
# training the logistic regression model in training set.
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

#### Predicting Test Set Results

In [13]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


#### Making Confusion Matrix and Accuracy

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy: ", accuracy_score(y_test, y_pred) * 100, "%")

[[5653  145]
 [ 506  286]]
accuracy:  90.12139605462822 %


# ---------- K-Nearest Neighbors ----------

In [15]:
# Training the K-NN model on the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

#### Predicting Test Set Results

In [16]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


#### Making Confusion Matrix and Accuracy

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy: ", accuracy_score(y_test, y_pred) * 100, "%")

[[5653  145]
 [ 574  218]]
accuracy:  89.08952959028832 %


# ---------- Support Vector Machine ----------

In [18]:
# # training SVM model on training set
# from sklearn.svm import SVC
# classifier = SVC(kernel = 'linear', random_state = 0)
# classifier.fit(x_train, y_train)

#### Predicting Test Set Results

In [19]:
# y_pred = classifier.predict(x_test)
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

#### Making Confusion Matrix and Accuracy

In [20]:
# from sklearn.metrics import confusion_matrix, accuracy_score
# cm = confusion_matrix(y_test, y_pred)
# print(cm)
# print("accuracy: ", accuracy_score(y_test, y_pred) * 100, "%")

# ---------- Kernal SVM ----------

In [21]:
# training kernal svm model on training set.
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(x_train, y_train)

SVC(random_state=0)

#### Predicting Test Set Results

In [22]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 1]]


#### Making Confusion Matrix and Accuracy

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy: ", accuracy_score(y_test, y_pred) * 100, "%")

[[5678  120]
 [ 540  252]]
accuracy:  89.98482549317147 %


# ---------- Naive Bayes ----------

In [24]:
# training naive bayes model on training set.
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

#### Predicting Test Set Results

In [25]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 0]
 [1 0]
 ...
 [0 0]
 [1 0]
 [1 1]]


#### Making Confusion Matrix and Accuracy

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy: ", accuracy_score(y_test, y_pred) * 100, "%")

[[ 223 5575]
 [   9  783]]
accuracy:  15.265553869499241 %


# ---------- Decision Tree Classification ----------

In [27]:
# training decision tree classification model on training set.
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

#### Predicting Test Set Result

In [28]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


#### Making Confusion Matrix and Accuracy

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy: ", accuracy_score(y_test, y_pred) * 100, "%")

[[5381  417]
 [ 426  366]]
accuracy:  87.20789074355083 %


# ---------- Random Forest Classification ----------

In [30]:
# training the model on training set.
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

#### Predicting Test Set Results

In [31]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 1]]


#### Making Confusion Matrix and Accuracy

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy: ", accuracy_score(y_test, y_pred) * 100, "%")

[[5638  160]
 [ 522  270]]
accuracy:  89.65098634294385 %


# ---------- Artificial Neural Network----------

In [33]:
import tensorflow as tf

In [34]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [35]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
ann.add(tf.keras.layers.Dense(units=1,kernel_initializer = 'uniform', activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(x_train, y_train, batch_size = 10, epochs = 200)

Epoch 1/200
2636/2636 [==============================] - 4s 1ms/step - loss: 0.2483 - accuracy: 0.8921
Epoch 2/200
2636/2636 [==============================] - 4s 1ms/step - loss: 0.2103 - accuracy: 0.9070
Epoch 3/200
2636/2636 [==============================] - 4s 1ms/step - loss: 0.2059 - accuracy: 0.9095
Epoch 4/200
2636/2636 [==============================] - 4s 1ms/step - loss: 0.2042 - accuracy: 0.9109
Epoch 5/200
2636/2636 [==============================] - 4s 1ms/step - loss: 0.2023 - accuracy: 0.9113
Epoch 6/200
2636/2636 [==============================] - 4s 1ms/step - loss: 0.2010 - accuracy: 0.9118
Epoch 7/200
2636/2636 [==============================] - 4s 1ms/step - loss: 0.1996 - accuracy: 0.9130
Epoch 8/200
2636/2636 [==============================] - 4s 1ms/step - loss: 0.1990 - accuracy: 0.9129
Epoch 9/200
2636/2636 [==============================] - 4s 2ms/step - loss: 0.1985 - accuracy: 0.9134
Epoch 10/200
2636/2636 [==============================] - 4s 1ms/step - l

2636/2636 [==============================] - 4s 1ms/step - loss: 0.1916 - accuracy: 0.9158
Epoch 158/200
2636/2636 [==============================] - 4s 2ms/step - loss: 0.1913 - accuracy: 0.9161
Epoch 159/200
2636/2636 [==============================] - 4s 1ms/step - loss: 0.1913 - accuracy: 0.9152
Epoch 160/200
2636/2636 [==============================] - 4s 1ms/step - loss: 0.1916 - accuracy: 0.9159
Epoch 161/200
2636/2636 [==============================] - 4s 1ms/step - loss: 0.1915 - accuracy: 0.9158
Epoch 162/200
2636/2636 [==============================] - 4s 1ms/step - loss: 0.1915 - accuracy: 0.9155
Epoch 163/200
2636/2636 [==============================] - 4s 1ms/step - loss: 0.1915 - accuracy: 0.9154
Epoch 164/200
2636/2636 [==============================] - 4s 1ms/step - loss: 0.1914 - accuracy: 0.9159
Epoch 165/200
2636/2636 [==============================] - 4s 1ms/step - loss: 0.1914 - accuracy: 0.9153
Epoch 166/200
2636/2636 [==============================] - 4s 1ms/ste

In [50]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy: ", accuracy_score(y_test, y_pred) * 100, "%")

[[5563  235]
 [ 385  407]]
accuracy:  90.59180576631259 %
